# Generated by Django 2.0.7 on 2018-08-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('update_changes', models.CharField(blank=True, max_length=150, null=True)),
                ('repository_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repo.repo')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
