# Generated by Django 2.0.7 on 2018-07-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/%H/%M/%S/')),
                ('update_changes', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
