# Generated by Django 2.0.7 on 2018-07-21 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadmodel',
            old_name='date_created',
            new_name='date',
        ),
    ]
