# Generated by Django 2.0.7 on 2018-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20180721_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='File_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadmodel',
            name='update_changes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
