# Generated by Django 2.0.7 on 2018-07-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20180723_1219'),
        ('file', '0003_auto_20180722_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadmodel',
            name='repository_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repo.repo'),
            preserve_default=False,
        ),
    ]
