# Generated by Django 2.0.7 on 2018-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
