# Generated by Django 2.0.7 on 2018-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
