# Generated by Django 2.0.7 on 2018-07-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Bio',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
