# Generated by Django 2.0.7 on 2018-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180722_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='Bio',
            field=models.TextField(blank=True, default=True),
        ),
    ]
