# Generated by Django 2.0.7 on 2018-07-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20180722_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='member',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
