# Generated by Django 2.0.7 on 2018-07-21 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repo',
            old_name='date',
            new_name='date_created',
        ),
    ]
