# Generated by Django 2.0.7 on 2018-07-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repo',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
