# Generated by Django 2.0.7 on 2018-07-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20180721_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
