# Generated by Django 2.0.7 on 2018-07-24 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20180723_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
