# Generated by Django 2.0.7 on 2018-07-21 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0004_auto_20180719_0222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadModel',
        ),
    ]
