# Generated by Django 2.0.7 on 2018-07-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0005_auto_20180724_0726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='owner',
        ),
    ]
